[base]
# HTTP 端口号
http_port=3030
# 存放文件的路径
source_path=./files
# 存放文件的缓存路径
source_temp_path=./files/temp
# 备份文件路径
backup_path=./backup
# 缓存驱动 (可选: redis, memory)
cache_drive=memory
# 队列驱动 (可选: redis, memory)
queue_drive=memory
# 数据库驱动 (可选: sqlite, mysql)
database_drive=sqlite

[sqlite]
# SQLite 数据库文件路径
file_path=./database.db

[mysql]
username=root
password=root
host=127.0.0.1
port=3306
db_name=sun_panel
wait_timeout=60

[redis]
address=127.0.0.1:6379
password=
prefix=sun_panel:
db=0
